// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqj4Q7CQC749_AcrT-s6CGMqDOcBq5Nk',
    appId: '1:802532634894:web:c23af3256b4223d254a75f',
    messagingSenderId: '802532634894',
    projectId: 'multi-store-d363d',
    authDomain: 'multi-store-d363d.firebaseapp.com',
    storageBucket: 'multi-store-d363d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyXLMsDCAZ5o46uI8cAq9rCeGoGhIBRo',
    appId: '1:802532634894:android:d54561a5b8cf61ee54a75f',
    messagingSenderId: '802532634894',
    projectId: 'multi-store-d363d',
    storageBucket: 'multi-store-d363d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWJXMrahDpIJ43t3g1jxedPmbRkNSvBY',
    appId: '1:802532634894:ios:d3c61be45f66c37a54a75f',
    messagingSenderId: '802532634894',
    projectId: 'multi-store-d363d',
    storageBucket: 'multi-store-d363d.appspot.com',
    androidClientId: '802532634894-tjunt1fp26hmiuaj8q81qogi39hs5dpl.apps.googleusercontent.com',
    iosClientId: '802532634894-sqoqgfgbbidego9fjnn9l56suh20tbjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEWJXMrahDpIJ43t3g1jxedPmbRkNSvBY',
    appId: '1:802532634894:ios:d3c61be45f66c37a54a75f',
    messagingSenderId: '802532634894',
    projectId: 'multi-store-d363d',
    storageBucket: 'multi-store-d363d.appspot.com',
    androidClientId: '802532634894-tjunt1fp26hmiuaj8q81qogi39hs5dpl.apps.googleusercontent.com',
    iosClientId: '802532634894-sqoqgfgbbidego9fjnn9l56suh20tbjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );
}
